jobs:
  include:
  - stage: unit tests
    os: linux
    language: python
    script:
    - pip3 install ./ 
    - svg2mod -i examples/svg2mod.svg -o output.kicad_mod -x -c -pads --name TEST --value VALUE -f 2 -p 1 --format pretty --units mm -d 300
    - svg2mod -i examples/svg2mod.svg
  - stage: deploy
    os: linux
    language: python
    script:
    - python setup.py bdist_wheel sdist
    deploy:
      provider: pypi
      username: "__token__"
      password:
        secure: "gcUUJQGNThihHXodH3AbLkr+mb7mNeB9z1bLaeAPqNU+xgP5mWeh8Cy/86T98GfOxLcfyxLi8bzDlZOBUqpQRGC5xghp8vEKJoecam1rLFnZyQk7MzttO3qIqSNiO7xsnsvkIKlRtxRi/8bn+I7lnHaISCLwfkyc6/3izlKX7nGSDARKWG6zYSLgD9X1pul1gOFVE7gcEle7ndU5sL89Vj6bZB8jnexsrG4ulKlzJPE0rDJpu94ByYOCJ9CjC4QAzcQ7bhomOEugRgWYhpeSaphaRQpBJgUSFkQ2Rc5tuygKXlWJrhuWn3URGFW15ZT1kfYZH8PNR+6ozeAKrjRoFGME040yEwaYvA1ms18G6VvCX41Eq4Veou3CGvIx9cGADhTxPO0Cc5gtgx6a3rHgLB1F62u+Bhcb5ALbdQl398Phri/mXTpAthsgpSn65GKnekmre8jUKFj9rnBkdBslLnjV1S0dJ2t1/hB6dirv/lsrv1QwFt0ig8NrFs6z2N+hI1A851XW9Gja32iCRaU/AL4cnpL4dVmF8LUQRMKaoncBrCjB0nW6SiU6Hw4SDdmhSVnDC0dW8pceslZ14vZaoUQkIkg1g5TcYQ/WWweBQpnwT97GpYBrrAlGpp36DY+LGj8e3VVQnhv6ORo5aiPfrSF4Kufn+uUIaaMetph7Xgk="
      cleanup: false
      on:
        branch: master
        tags: true
