jobs:
  include:
  - stage: unit tests
    os: linux
    language: python
    script:
    - pip3 install ./ 
    - svg2mod -i examples/svg2mod.svg -o output.kicad_mod -x -c -pads --name TEST --value VALUE -f 2 -p 1 --format pretty --units mm -d 300
    - svg2mod -i examples/svg2mod.svg
  - stage: deploy
    os: linux
    language: python
    script:
    - python setup.py bdist_wheel sdist
    deploy:
      provider: pypi
      username: "__token__"
      password:
        secure: "VkDOh68XBeP6bZrCnBmWoKz2eRZeKek/29M2tzC3I42wci2KFWCRJEiXfIAq1qwl4lw1RUVtSc6XrJNskgxKVrZgGNZTp7slLZNOBRMA/A/NHwF65OuBxwPta9o0l5kUWYc72AkXUD/uaWN9NLrJrMw/HSoFPdl8reWzJq4zUpJPP0/dDvcNe4oFbqUvDdV9ZaVbd9m9kvaY/KvjCiJ36tTRHFac66y5fLz3heKVPwXQT+qYG2NCM1o8Iik16+zCbxIrTtHCpb8sYXTmHBuVHacmy2xG1TPIvkIG+toSfK+cQHBLjyZXIcgfmIlusxQ+Acdv2QSDOT1Miyhdz+MRFYC7UQIDQn39mE4gLOy9ljYoU/v4TwzZ5xjC0cfp9D3N2Bt7STkM9u/Ft6jEXsVfvJ0MbHu4UDk/xK5AngDk8g3F46sje01yfc8D43Ghgb4Ixd9i76VkXm6RRSKZwCtR1DYYYTS93yAKdALj7qdEMzbANURGI1ly9bkWWRcz30LB1Ufon6gO5LdU0mzjGEj2Yl2n22RKCtLG0mNo+I9xrXcicfpCn4mbQ25o1dvbG2ROYFWXYa/yaK/K/PjtAHa2sFEiuqSDlUFd/qfjB+37u/QPuxZSf99P5KBQ4Pc0pvCjOlGqHWI6jzhPp/S6DnyXGykuPn8/IATe9FrUFkEjDlo="
      server: "https://test.pypi.org/legacy/"
      cleanup: false
      on:
        tags: true
